name: Lint And Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: lint and test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - run: make prepare
    - run: make lint
    - run: make test
